#!/usr/bin/env bash
# displays the numbers 1 to 20 and displays
#+ "bad luck from China" after the 4th loop iteration
#+ "bad luck from Japan" after the 9th loop iteration
#+ "bad luck from Italy" after the 17th loop iteration

i=1

while [ $i -le 20 ]; do
	case $i in
	4)
		echo -e "$i\nbad luck from China"
		;;
	9)
		echo -e "$i\nbad luck from Japan"
		;;
	17)
		echo -e "$i\nbad luck from Italy"
		;;
	*)
		echo "$i"
		;;
	esac
	((i+=1))
done
